[2022-06-06 11:06:44,639] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.drop_order_detail_table scheduled__2022-06-05T00:00:00+00:00 [queued]>
[2022-06-06 11:06:44,657] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.drop_order_detail_table scheduled__2022-06-05T00:00:00+00:00 [queued]>
[2022-06-06 11:06:44,658] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 11:06:44,659] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-06 11:06:44,660] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 11:06:44,684] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): drop_order_detail_table> on 2022-06-05 00:00:00+00:00
[2022-06-06 11:06:44,691] {standard_task_runner.py:52} INFO - Started process 455 to run task
[2022-06-06 11:06:44,700] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'drop_order_detail_table', 'scheduled__2022-06-05T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpbkfvqh6c', '--error-file', '/tmp/tmpxyz0v8ub']
[2022-06-06 11:06:44,704] {standard_task_runner.py:80} INFO - Job 7: Subtask drop_order_detail_table
[2022-06-06 11:06:44,804] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.drop_order_detail_table scheduled__2022-06-05T00:00:00+00:00 [running]> on host 0c241499c9fe
[2022-06-06 11:06:44,930] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pathairs
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=drop_order_detail_table
AIRFLOW_CTX_EXECUTION_DATE=2022-06-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-05T00:00:00+00:00
[2022-06-06 11:06:45,183] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 181, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 86, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_db` isn't defined
[2022-06-06 11:06:45,190] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=hands_on_test, task_id=drop_order_detail_table, execution_date=20220605T000000, start_date=20220606T110644, end_date=20220606T110645
[2022-06-06 11:06:45,398] {standard_task_runner.py:97} ERROR - Failed to execute job 7 for task drop_order_detail_table (The conn_id `postgres_db` isn't defined; 455)
[2022-06-06 11:06:45,436] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-06 11:06:45,526] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-06-06 11:43:00,730] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.drop_order_detail_table scheduled__2022-06-05T00:00:00+00:00 [queued]>
[2022-06-06 11:43:00,744] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.drop_order_detail_table scheduled__2022-06-05T00:00:00+00:00 [queued]>
[2022-06-06 11:43:00,745] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 11:43:00,746] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-06 11:43:00,747] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 11:43:00,766] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): drop_order_detail_table> on 2022-06-05 00:00:00+00:00
[2022-06-06 11:43:00,772] {standard_task_runner.py:52} INFO - Started process 3135 to run task
[2022-06-06 11:43:00,777] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'drop_order_detail_table', 'scheduled__2022-06-05T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmptu8ommlv', '--error-file', '/tmp/tmpppwfh7aw']
[2022-06-06 11:43:00,780] {standard_task_runner.py:80} INFO - Job 48: Subtask drop_order_detail_table
[2022-06-06 11:43:00,855] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.drop_order_detail_table scheduled__2022-06-05T00:00:00+00:00 [running]> on host 0c241499c9fe
[2022-06-06 11:43:00,965] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pathairs
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=drop_order_detail_table
AIRFLOW_CTX_EXECUTION_DATE=2022-06-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-05T00:00:00+00:00
[2022-06-06 11:43:00,982] {base.py:68} INFO - Using connection ID 'postgres_db' for task execution.
[2022-06-06 11:43:00,996] {dbapi.py:208} INFO - Running statement: 
DROP TABLE IF EXISTS order_detail;, parameters: None
[2022-06-06 11:43:01,179] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=hands_on_test, task_id=drop_order_detail_table, execution_date=20220605T000000, start_date=20220606T114300, end_date=20220606T114301
[2022-06-06 11:43:01,474] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-06 11:43:01,552] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-06-06 12:14:43,345] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.drop_order_detail_table scheduled__2022-06-05T00:00:00+00:00 [queued]>
[2022-06-06 12:14:43,358] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.drop_order_detail_table scheduled__2022-06-05T00:00:00+00:00 [queued]>
[2022-06-06 12:14:43,359] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 12:14:43,360] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-06 12:14:43,361] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 12:14:43,381] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): drop_order_detail_table> on 2022-06-05 00:00:00+00:00
[2022-06-06 12:14:43,391] {standard_task_runner.py:52} INFO - Started process 1909 to run task
[2022-06-06 12:14:43,395] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'drop_order_detail_table', 'scheduled__2022-06-05T00:00:00+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpz9s_did4', '--error-file', '/tmp/tmp2pxb0dvg']
[2022-06-06 12:14:43,398] {standard_task_runner.py:80} INFO - Job 73: Subtask drop_order_detail_table
[2022-06-06 12:14:43,489] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.drop_order_detail_table scheduled__2022-06-05T00:00:00+00:00 [running]> on host 078df8b61ea1
[2022-06-06 12:14:43,608] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pathairs
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=drop_order_detail_table
AIRFLOW_CTX_EXECUTION_DATE=2022-06-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-05T00:00:00+00:00
[2022-06-06 12:14:43,621] {base.py:68} INFO - Using connection ID 'postgres_db' for task execution.
[2022-06-06 12:14:43,638] {dbapi.py:208} INFO - Running statement: 
DROP TABLE IF EXISTS order_detail;, parameters: None
[2022-06-06 12:14:43,676] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=hands_on_test, task_id=drop_order_detail_table, execution_date=20220605T000000, start_date=20220606T121443, end_date=20220606T121443
[2022-06-06 12:14:43,930] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-06 12:14:44,014] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
