[2022-06-10 07:02:46,844] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.copy_order_data manual__2022-06-10T06:57:39.204816+00:00 [queued]>
[2022-06-10 07:02:46,863] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.copy_order_data manual__2022-06-10T06:57:39.204816+00:00 [queued]>
[2022-06-10 07:02:46,864] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-10 07:02:46,865] {taskinstance.py:1357} INFO - Starting attempt 4 of 5
[2022-06-10 07:02:46,866] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-10 07:02:46,886] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): copy_order_data> on 2022-06-10 06:57:39.204816+00:00
[2022-06-10 07:02:46,892] {standard_task_runner.py:52} INFO - Started process 727 to run task
[2022-06-10 07:02:46,897] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'copy_order_data', 'manual__2022-06-10T06:57:39.204816+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpu6br2vnz', '--error-file', '/tmp/tmphqd30af2']
[2022-06-10 07:02:46,899] {standard_task_runner.py:80} INFO - Job 33: Subtask copy_order_data
[2022-06-10 07:02:46,983] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.copy_order_data manual__2022-06-10T06:57:39.204816+00:00 [running]> on host a0fd966c00bf
[2022-06-10 07:02:47,091] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=copy_order_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-10T06:57:39.204816+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-10T06:57:39.204816+00:00
[2022-06-10 07:02:47,093] {mysql.py:82} INFO - Executing: 
COPY orders FROM '/var/lib/mysql/data/test/Orders.csv' DELIMITER ',' CSV HEADER;
[2022-06-10 07:02:47,109] {base.py:68} INFO - Using connection ID 'mysql_db' for task execution.
[2022-06-10 07:02:47,150] {dbapi.py:208} INFO - Running statement: 
COPY orders FROM '/var/lib/mysql/data/test/Orders.csv' DELIMITER ',' CSV HEADER;, parameters: None
[2022-06-10 07:02:47,153] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/operators/mysql.py", line 84, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 188, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 212, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'COPY orders FROM '/var/lib/mysql/data/test/Orders.csv' DELIMITER ',' CSV HEADER' at line 1")
[2022-06-10 07:02:47,166] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=hands_on_test, task_id=copy_order_data, execution_date=20220610T065739, start_date=20220610T070246, end_date=20220610T070247
[2022-06-10 07:02:47,182] {standard_task_runner.py:97} ERROR - Failed to execute job 33 for task copy_order_data ((1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'COPY orders FROM '/var/lib/mysql/data/test/Orders.csv' DELIMITER ',' CSV HEADER' at line 1"); 727)
[2022-06-10 07:02:47,231] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-10 07:02:47,315] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
