[2022-06-08 10:27:04,461] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.copy_order_data manual__2022-06-08T07:26:45.844950+00:00 [queued]>
[2022-06-08 10:27:04,476] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.copy_order_data manual__2022-06-08T07:26:45.844950+00:00 [queued]>
[2022-06-08 10:27:04,477] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-08 10:27:04,478] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-08 10:27:04,479] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-08 10:27:04,501] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): copy_order_data> on 2022-06-08 07:26:45.844950+00:00
[2022-06-08 10:27:04,508] {standard_task_runner.py:52} INFO - Started process 30239 to run task
[2022-06-08 10:27:04,517] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'copy_order_data', 'manual__2022-06-08T07:26:45.844950+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpm34sg0kx', '--error-file', '/tmp/tmph9172y6w']
[2022-06-08 10:27:04,519] {standard_task_runner.py:80} INFO - Job 228: Subtask copy_order_data
[2022-06-08 10:27:04,610] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.copy_order_data manual__2022-06-08T07:26:45.844950+00:00 [running]> on host b79bd65fcc57
[2022-06-08 10:27:04,714] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=copy_order_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-08T07:26:45.844950+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-08T07:26:45.844950+00:00
[2022-06-08 10:27:04,716] {mysql.py:82} INFO - Executing: 
COPY orders FROM '/var/lib/mysql/data/dataset/Orders.csv' DELIMITER ',' CSV HEADER;
[2022-06-08 10:27:04,730] {base.py:68} INFO - Using connection ID 'mysql_db' for task execution.
[2022-06-08 10:27:04,793] {dbapi.py:208} INFO - Running statement: 
COPY orders FROM '/var/lib/mysql/data/dataset/Orders.csv' DELIMITER ',' CSV HEADER;, parameters: None
[2022-06-08 10:27:04,803] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/operators/mysql.py", line 84, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 188, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 212, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.7/site-packages/MySQLdb/connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'COPY orders FROM '/var/lib/mysql/data/dataset/Orders.csv' DELIMITER ',' CSV HEAD' at line 1")
[2022-06-08 10:27:04,826] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=hands_on_test, task_id=copy_order_data, execution_date=20220608T072645, start_date=20220608T102704, end_date=20220608T102704
[2022-06-08 10:27:04,859] {standard_task_runner.py:97} ERROR - Failed to execute job 228 for task copy_order_data ((1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'COPY orders FROM '/var/lib/mysql/data/dataset/Orders.csv' DELIMITER ',' CSV HEAD' at line 1"); 30239)
[2022-06-08 10:27:04,892] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-08 10:27:04,976] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
