[2022-06-07 04:28:14,589] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.install_sqoop scheduled__2022-06-06T00:00:00+00:00 [queued]>
[2022-06-07 04:28:14,603] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.install_sqoop scheduled__2022-06-06T00:00:00+00:00 [queued]>
[2022-06-07 04:28:14,604] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-07 04:28:14,605] {taskinstance.py:1357} INFO - Starting attempt 10 of 10
[2022-06-07 04:28:14,605] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-07 04:28:14,626] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): install_sqoop> on 2022-06-06 00:00:00+00:00
[2022-06-07 04:28:14,637] {standard_task_runner.py:52} INFO - Started process 941 to run task
[2022-06-07 04:28:14,643] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'install_sqoop', 'scheduled__2022-06-06T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpk23yxcca', '--error-file', '/tmp/tmpsc5_55th']
[2022-06-07 04:28:14,645] {standard_task_runner.py:80} INFO - Job 27: Subtask install_sqoop
[2022-06-07 04:28:14,724] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.install_sqoop scheduled__2022-06-06T00:00:00+00:00 [running]> on host 656095cefd6b
[2022-06-07 04:28:14,822] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pathairs
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=install_sqoop
AIRFLOW_CTX_EXECUTION_DATE=2022-06-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=10
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-06T00:00:00+00:00
[2022-06-07 04:28:14,824] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-07 04:28:14,826] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker exec hive-server bash /opt/sqoop/install_sqoop.sh ']
[2022-06-07 04:28:14,838] {subprocess.py:85} INFO - Output:
[2022-06-07 04:28:14,891] {subprocess.py:92} INFO - Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/hive-server/json": dial unix /var/run/docker.sock: connect: permission denied
[2022-06-07 04:28:14,896] {subprocess.py:96} INFO - Command exited with return code 1
[2022-06-07 04:28:14,914] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-06-07 04:28:14,920] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=hands_on_test, task_id=install_sqoop, execution_date=20220606T000000, start_date=20220607T042814, end_date=20220607T042814
[2022-06-07 04:28:14,935] {standard_task_runner.py:97} ERROR - Failed to execute job 27 for task install_sqoop (Bash command failed. The command returned a non-zero exit code 1.; 941)
[2022-06-07 04:28:14,976] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-07 04:28:15,038] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
