[2022-06-07 03:18:17,123] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.install_sqoop scheduled__2022-06-06T00:00:00+00:00 [queued]>
[2022-06-07 03:18:17,142] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.install_sqoop scheduled__2022-06-06T00:00:00+00:00 [queued]>
[2022-06-07 03:18:17,143] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-07 03:18:17,144] {taskinstance.py:1357} INFO - Starting attempt 4 of 4
[2022-06-07 03:18:17,145] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-07 03:18:17,171] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): install_sqoop> on 2022-06-06 00:00:00+00:00
[2022-06-07 03:18:17,179] {standard_task_runner.py:52} INFO - Started process 1765 to run task
[2022-06-07 03:18:17,184] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'install_sqoop', 'scheduled__2022-06-06T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmppuay52ew', '--error-file', '/tmp/tmpvn_0qsjx']
[2022-06-07 03:18:17,187] {standard_task_runner.py:80} INFO - Job 20: Subtask install_sqoop
[2022-06-07 03:18:17,267] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.install_sqoop scheduled__2022-06-06T00:00:00+00:00 [running]> on host 90bb19738779
[2022-06-07 03:18:17,365] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=pathairs
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=install_sqoop
AIRFLOW_CTX_EXECUTION_DATE=2022-06-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-06T00:00:00+00:00
[2022-06-07 03:18:17,367] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-06-07 03:18:17,369] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'docker exec hive-server bash /opt/sqoop/install_sqoop.sh ']
[2022-06-07 03:18:17,380] {subprocess.py:85} INFO - Output:
[2022-06-07 03:18:17,427] {subprocess.py:92} INFO - Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/hive-server/json": dial unix /var/run/docker.sock: connect: permission denied
[2022-06-07 03:18:17,431] {subprocess.py:96} INFO - Command exited with return code 1
[2022-06-07 03:18:17,452] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-06-07 03:18:17,457] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=hands_on_test, task_id=install_sqoop, execution_date=20220606T000000, start_date=20220607T031817, end_date=20220607T031817
[2022-06-07 03:18:17,472] {standard_task_runner.py:97} ERROR - Failed to execute job 20 for task install_sqoop (Bash command failed. The command returned a non-zero exit code 1.; 1765)
[2022-06-07 03:18:17,517] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-07 03:18:17,578] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
