[2022-06-08 10:27:57,038] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.postgreq_data_quality_check manual__2022-06-08T07:26:45.844950+00:00 [queued]>
[2022-06-08 10:27:57,055] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.postgreq_data_quality_check manual__2022-06-08T07:26:45.844950+00:00 [queued]>
[2022-06-08 10:27:57,056] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-08 10:27:57,056] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-08 10:27:57,057] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-08 10:27:57,076] {taskinstance.py:1377} INFO - Executing <Task(PostgresDataQualityOperator): postgreq_data_quality_check> on 2022-06-08 07:26:45.844950+00:00
[2022-06-08 10:27:57,081] {standard_task_runner.py:52} INFO - Started process 30302 to run task
[2022-06-08 10:27:57,090] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'postgreq_data_quality_check', 'manual__2022-06-08T07:26:45.844950+00:00', '--job-id', '229', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp4r7h7vkw', '--error-file', '/tmp/tmp46s2bpdl']
[2022-06-08 10:27:57,092] {standard_task_runner.py:80} INFO - Job 229: Subtask postgreq_data_quality_check
[2022-06-08 10:27:57,173] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.postgreq_data_quality_check manual__2022-06-08T07:26:45.844950+00:00 [running]> on host b79bd65fcc57
[2022-06-08 10:27:57,281] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=postgreq_data_quality_check
AIRFLOW_CTX_EXECUTION_DATE=2022-06-08T07:26:45.844950+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-08T07:26:45.844950+00:00
[2022-06-08 10:27:57,283] {data_quality.py:20} INFO - DataQualityOperator
[2022-06-08 10:27:57,296] {base.py:68} INFO - Using connection ID 'postgres_db' for task execution.
[2022-06-08 10:27:57,429] {base.py:68} INFO - Using connection ID 'postgres_db' for task execution.
[2022-06-08 10:27:57,458] {base.py:68} INFO - Using connection ID 'postgres_db' for task execution.
[2022-06-08 10:27:57,476] {data_quality.py:36} WARNING - Data quality check passed
[2022-06-08 10:27:57,499] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=hands_on_test, task_id=postgreq_data_quality_check, execution_date=20220608T072645, start_date=20220608T102757, end_date=20220608T102757
[2022-06-08 10:27:57,541] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-08 10:27:57,625] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
