[2022-06-08 03:42:10,255] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.postgreq_data_quality_check manual__2022-06-08T02:39:54.959518+00:00 [queued]>
[2022-06-08 03:42:10,274] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: hands_on_test.postgreq_data_quality_check manual__2022-06-08T02:39:54.959518+00:00 [queued]>
[2022-06-08 03:42:10,275] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-08 03:42:10,276] {taskinstance.py:1357} INFO - Starting attempt 4 of 5
[2022-06-08 03:42:10,276] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-08 03:42:10,298] {taskinstance.py:1377} INFO - Executing <Task(PostgresDataQualityOperator): postgreq_data_quality_check> on 2022-06-08 02:39:54.959518+00:00
[2022-06-08 03:42:10,304] {standard_task_runner.py:52} INFO - Started process 4770 to run task
[2022-06-08 03:42:10,310] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'hands_on_test', 'postgreq_data_quality_check', 'manual__2022-06-08T02:39:54.959518+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpycf9fhxs', '--error-file', '/tmp/tmpqqj12c4x']
[2022-06-08 03:42:10,312] {standard_task_runner.py:80} INFO - Job 92: Subtask postgreq_data_quality_check
[2022-06-08 03:42:10,426] {task_command.py:369} INFO - Running <TaskInstance: hands_on_test.postgreq_data_quality_check manual__2022-06-08T02:39:54.959518+00:00 [running]> on host b79bd65fcc57
[2022-06-08 03:42:10,559] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=hands_on_test
AIRFLOW_CTX_TASK_ID=postgreq_data_quality_check
AIRFLOW_CTX_EXECUTION_DATE=2022-06-08T02:39:54.959518+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-08T02:39:54.959518+00:00
[2022-06-08 03:42:10,564] {data_quality.py:20} INFO - DataQualityOperator
[2022-06-08 03:42:10,581] {base.py:68} INFO - Using connection ID 'postgres_db' for task execution.
[2022-06-08 03:42:10,668] {base.py:68} INFO - Using connection ID 'postgres_db' for task execution.
[2022-06-08 03:42:10,695] {data_quality.py:36} WARNING - Data quality check passed
[2022-06-08 03:42:10,728] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=hands_on_test, task_id=postgreq_data_quality_check, execution_date=20220608T023954, start_date=20220608T034210, end_date=20220608T034210
[2022-06-08 03:42:10,766] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-08 03:42:10,839] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
